# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
        #push:
        #pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_readme:
      runs-on: ubuntu-latest
      steps:
        - name: Make Sky130HD Temp
          env:
                IMAGE_NAME: saicharan0112/openfasoc_ci:latest
          run: |
            docker run --rm\
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              git clone https://github.com/saicharan0112/OpenFASOC.git &&\
              cd OpenFASOC &&\
              /scripts/extract_commit_no.sh > commits.txt &&\
              /scripts/modify_readme.py"
              