# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sky130hd_temp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Make Sky130HD Temp
        env:
                IMAGE_NAME: saicharan0112/openfasoc_ci:latest
        run: |
          cd $GITHUB_WORKSPACE
          touch file.log
          docker run --rm\
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              export PDK_ROOT=/pdk_data/ &&\
              cd ./openfasoc/generators/temp-sense-gen &&\
              make sky130hd_temp\
            ">> file.log
            if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi
